<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- Rain World 核心引用 -->
    <Reference
      Include="C:\Program Files (x86)\Steam\steamapps\common\Rain World\RainWorld_Data\Managed\*.dll" />
    <Reference
      Include="C:\Program Files (x86)\Steam\steamapps\common\Rain World\BepInEx\plugins\*.dll" />
    <Reference Include="C:\Program Files (x86)\Steam\steamapps\common\Rain World\BepInEx\core\*.dll" />
    <Reference
      Include="C:\Program Files (x86)\Steam\steamapps\common\Rain World\BepInEx\utils\*.dll" />

    <!-- MOD 依赖 -->
    <Reference
      Include="C:\Program Files (x86)\Steam\steamapps\workshop\content\312520\2933196558\newest\plugins\slugbase.dll" />
    <Reference
      Include="C:\Program Files (x86)\Steam\steamapps\workshop\content\312520\2920541687\newest\plugins\*.dll" />
    <Reference
      Include="C:\Program Files (x86)\Steam\steamapps\workshop\content\312520\3388224007\plugins\*.dll" />
  </ItemGroup>

  <Target Name="GenerateMod" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <RemovePlugins Include="../mod/newest/plugins/*.dll" />
    </ItemGroup>

    <ItemGroup>
      <CopyPlugins Include="$(TargetPath);$(TargetDir)$(TargetName).pdb" />
    </ItemGroup>

    <Delete Files="@(RemovePlugins)" />
    <Copy SourceFiles="@(CopyPlugins)" DestinationFolder="../mod/newest/plugins/" />

  </Target>
</Project>